server:
  port: 6060

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service1
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment-service1
          predicates:
            - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    health:
      probes:
        enabled: true