pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Jar') {
    steps {
        dir('order-service1') {
            bat 'mvn  clean package -DskipTests'
        }
    }
}

        stage('Docker Build') {
            steps {
                bat 'docker build -t order-service1:latest .'
            }
        }

        stage('Deploy To Kubernetes') {
            steps {
                bat 'kubectl apply -f k8s/'
            }
        }
    }
}