pipeline {

    agent any

tools {
        // This MUST match the exact Name you typed in Jenkins UI
        maven 'apache-maven-3.9.6' 
    }
	
    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Jar') {
    steps {
        dir('payment-service1') {
            bat 'mvn clean package -DskipTests'
        }
    }
}

        stage('Docker Build') {
            steps {
                bat 'docker build -t payment-service1:latest .'
            }
        }

        stage('Deploy To Kubernetes') {
            steps {
                bat 'kubectl apply -f k8s/'
            }
        }
    }
}