apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway1

    spec:
      containers:
        - name: api-gateway1

          image: api-gateway1:latest

          imagePullPolicy: Never

          ports:
            - containerPort: 6060

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 6060
            initialDelaySeconds: 20

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 6060
            initialDelaySeconds: 20