server:
  port: 6061

spring:
  application:
    name: order-service1

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,info

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true