pipeline {

    agent any

    environment {
        IMAGE_NAME = "api-gateway1"
        IMAGE_TAG  = "latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Jar') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% .'
            }
        }

        stage('Deploy To Kubernetes') {
            steps {
                bat 'kubectl apply -f k8s/'
            }
        }

    }

    post {

        success {
            echo 'API Gateway deployed successfully'
        }

        failure {
            echo 'Build or deployment failed'
        }

    }
}